// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OnlineBank.Migrations
{
    [DbContext(typeof(OnlineBankContext))]
    partial class OnlineBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineBank.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.HasIndex("ClientID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OnlineBank.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Permissions")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("OnlineBank.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("OnlineBank.Models.Friendship", b =>
                {
                    b.Property<int?>("FriendshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Friend1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Friend2ID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("FriendshipID");

                    b.HasIndex("Friend1ID");

                    b.HasIndex("Friend2ID");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("OnlineBank.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OnlineBank.Models.SocialLoan", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Account1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Account2ID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LoanID");

                    b.HasIndex("Account1ID");

                    b.HasIndex("Account2ID");

                    b.ToTable("SocialLoans");
                });

            modelBuilder.Entity("OnlineBank.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Account1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Account2ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TransactionID");

                    b.HasIndex("Account1ID");

                    b.HasIndex("Account2ID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnlineBank.Models.Account", b =>
                {
                    b.HasOne("OnlineBank.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OnlineBank.Models.Friendship", b =>
                {
                    b.HasOne("OnlineBank.Models.Client", "Client1")
                        .WithMany()
                        .HasForeignKey("Friend1ID");

                    b.HasOne("OnlineBank.Models.Client", "Client2")
                        .WithMany()
                        .HasForeignKey("Friend2ID");

                    b.Navigation("Client1");

                    b.Navigation("Client2");
                });

            modelBuilder.Entity("OnlineBank.Models.SocialLoan", b =>
                {
                    b.HasOne("OnlineBank.Models.Account", "Account1")
                        .WithMany()
                        .HasForeignKey("Account1ID");

                    b.HasOne("OnlineBank.Models.Account", "Account2")
                        .WithMany()
                        .HasForeignKey("Account2ID");

                    b.Navigation("Account1");

                    b.Navigation("Account2");
                });

            modelBuilder.Entity("OnlineBank.Models.Transaction", b =>
                {
                    b.HasOne("OnlineBank.Models.Account", "Account1")
                        .WithMany()
                        .HasForeignKey("Account1ID");

                    b.HasOne("OnlineBank.Models.Account", "Account2")
                        .WithMany()
                        .HasForeignKey("Account2ID");

                    b.Navigation("Account1");

                    b.Navigation("Account2");
                });
#pragma warning restore 612, 618
        }
    }
}
